id: Checkerindi_Hash
version: -1
name: Checkerindi_Hash
description: Checks for hash reputation using Virus Total. Screenshot mode is enabled.
  Used as sub-playbook.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: df3f43a7-2c41-4a80-88c3-9be86798d166
    type: start
    task:
      id: df3f43a7-2c41-4a80-88c3-9be86798d166
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 00babb2e-d166-4526-81ea-fabcfa1e2b7e
    type: regular
    task:
      id: 00babb2e-d166-4526-81ea-fabcfa1e2b7e
      version: -1
      name: Virus Total Hash
      description: Checks virus total reputation for ip or url or hash or file
      script: Checker|||checkerindi-virustotal
      type: regular
      iscommand: true
      brand: Checker
    scriptarguments:
      indicator:
        simple: ${inputs.hash}
      mode:
        simple: hash
      screenshot:
        simple: "false"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs:
- key: hash
  value: {}
  required: false
  description: File
  playbookInputQuery:
outputs:
- contextPath: File.MD5
- contextPath: File.SHA1
- contextPath: File.SHA256
- contextPath: DBotScore.Indicator
- contextPath: DBotScore.Type
- contextPath: DBotScore.Vendor
- contextPath: DBotScore.Score
- contextPath: Checker.File.VirusTotal.score
- contextPath: Checker.File.VirusTotal.malicious
fromversion: 5.0.0
tests:
- No tests (auto formatted)
