id: Checker_Batch_IP
version: -1
name: Checker_Batch_IP
description: 'All-in-one automation: IP reputation check is carried out from a list
  of ip address provided in csv or text file.  CSV or text file should contain a column
  (1st column) of ip addresses without headers.'
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: b4395454-cb9e-42ec-8a3d-f63694e2e617
    type: start
    task:
      id: b4395454-cb9e-42ec-8a3d-f63694e2e617
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: af9ecadd-cac1-4cbe-8885-1b2f18a5e53c
    type: regular
    task:
      id: af9ecadd-cac1-4cbe-8885-1b2f18a5e53c
      version: -1
      name: Check Reputation of different IP addresses
      description: Check in batch the reputation of URL, Hash, IP and files  using
        OSINTs
      script: Checker|||checker-batch
      type: regular
      iscommand: true
      brand: Checker
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
      hashes: {}
      ips: {}
      mode:
        simple: ip
      screenshot:
        simple: ${inputs.screenshot mode}
      screenshot mode:
        simple: ${inputs.screenshot mode}
      urls: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 255,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs:
- key: csv file
  value:
    simple: ${File}
  required: false
  description: ""
  playbookInputQuery:
- key: screenshot mode
  value:
    complex:
      root: incident
      filters:
      - - operator: containsGeneral
          left:
            value:
              simple: incident.details
            iscontext: true
          right:
            value:
              simple: screenshot
      accessor: details
      transformers:
      - operator: substringFrom
        args:
          from:
            value:
              simple: screenshot
      - operator: trim
      - operator: toLowerCase
  required: false
  description: ""
  playbookInputQuery:
outputs:
- contextPath: IP.Verdict
  type: unknown
- contextPath: IP.Address
  type: unknown
- contextPath: DBotScore.Indicator
- contextPath: DBotScore.Type
- contextPath: DBotScore.Score
- contextPath: DBotScore.Vendor
fromversion: 5.0.0
tests:
- No tests (auto formatted)
