id: ee38a97f-c998-4d8f-8e5e-69cb7a59dd8b
version: 9
name: Checkerindi_Batch_Hash
description: Hash reputation check is carried out from a list of hashes provided in
  csv or text file.  CSV or text file should contain a column (1st column) of hashes
  without headers.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 19d04886-0fc6-401c-8d7c-7ce8d4881877
    type: start
    task:
      id: 19d04886-0fc6-401c-8d7c-7ce8d4881877
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "24"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -180,
          "y": 290
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "21":
    id: "21"
    taskid: 4f2fd971-ac05-4cb0-8d85-7f61bf08c011
    type: condition
    task:
      id: 4f2fd971-ac05-4cb0-8d85-7f61bf08c011
      version: -1
      name: Is it screenshot mode?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "28"
      "yes":
      - "29"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isTrue
          left:
            value:
              simple: inputs.screenshot mode
            iscontext: true
    view: |-
      {
        "position": {
          "x": -180,
          "y": 560
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "24":
    id: "24"
    taskid: d05905dc-610b-468f-8c94-6ff441bb058a
    type: regular
    task:
      id: d05905dc-610b-468f-8c94-6ff441bb058a
      version: -1
      name: Extract all Hash
      description: Extract a list of IPs, URLs or Hashes from te first column of the
        CSV or every line from text file
      script: Checker|||checkerindi-extract-single
      type: regular
      iscommand: true
      brand: Checker
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
      mode:
        simple: hash
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -180,
          "y": 410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "25":
    id: "25"
    taskid: 127382d8-14dc-4c26-8e4b-0d129f18787b
    type: regular
    task:
      id: 127382d8-14dc-4c26-8e4b-0d129f18787b
      version: -1
      name: Return files
      description: Returns results from checkerindi functions by returning CSV file
        and ZIP file if screenshot mode
      script: Checker|||checkerindi-results
      type: regular
      iscommand: true
      brand: Checker
    scriptarguments:
      filename: {}
      mode:
        simple: hash
      screenshot:
        simple: "false"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 40,
          "y": 890
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "27":
    id: "27"
    taskid: 2b18091d-70c6-4750-8921-4b5bccda25d9
    type: regular
    task:
      id: 2b18091d-70c6-4750-8921-4b5bccda25d9
      version: -1
      name: Return files
      description: Returns results from checkerindi functions by returning CSV file
        and ZIP file if screenshot mode
      script: Checker|||checkerindi-results
      type: regular
      iscommand: true
      brand: Checker
    scriptarguments:
      filename: {}
      mode:
        simple: hash
      screenshot:
        simple: "true"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -410,
          "y": 890
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "28":
    id: "28"
    taskid: 6091b8b0-9b9b-4d82-8d94-1977cdc10a18
    type: playbook
    task:
      id: 6091b8b0-9b9b-4d82-8d94-1977cdc10a18
      version: -1
      name: Checkerindi_Hash
      playbookName: Checkerindi_Hash
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "25"
    scriptarguments:
      hash:
        simple: ${Hash}
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
      forEach: true
    view: |-
      {
        "position": {
          "x": 40,
          "y": 740
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "29":
    id: "29"
    taskid: 11429c5a-3b2e-4ea1-8b1f-28c0f6f7ec99
    type: playbook
    task:
      id: 11429c5a-3b2e-4ea1-8b1f-28c0f6f7ec99
      version: -1
      name: Checkerindi_Hash_Screenshot
      playbookName: Checkerindi_Hash_Screenshot
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "27"
    scriptarguments:
      hash:
        simple: ${Hash}
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
      forEach: true
    view: |-
      {
        "position": {
          "x": -410,
          "y": 740
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 695,
        "width": 830,
        "x": -410,
        "y": 290
      }
    }
  }
inputs:
- key: file
  value:
    simple: ${File}
  required: false
  description: File reputation check
  playbookInputQuery: null
- key: screenshot mode
  value:
    complex:
      root: incident
      filters:
      - - operator: containsString
          left:
            value:
              simple: incident.details
            iscontext: true
          right:
            value:
              simple: screenshot
      accessor: details
      transformers:
      - operator: substringFrom
        args:
          from:
            value:
              simple: screenshot
      - operator: trim
      - operator: toLowerCase
  required: false
  description: ""
  playbookInputQuery: null
outputs:
- contextPath: DBotScore.Indicator
- contextPath: IP.Address
- contextPath: IP.VirusTotal.Score
- contextPath: IP.VirusTotal.Malicious
sourceplaybookid: 46bbae12-8fbc-4f3a-83a1-772e35af3e85
