id: Checkerindi_Batch_IP
version: -1
name: Checkerindi_Batch_IP
description: IP reputation check is carried out from a list of ip address provided
  in csv or text file.  CSV or text file should contain a column (1st column) of ip
  addresses without headers.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 19d04886-0fc6-401c-8d7c-7ce8d4881877
    type: start
    task:
      id: 19d04886-0fc6-401c-8d7c-7ce8d4881877
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "24"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -180,
          "y": 290
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "21":
    id: "21"
    taskid: 4f2fd971-ac05-4cb0-8d85-7f61bf08c011
    type: condition
    task:
      id: 4f2fd971-ac05-4cb0-8d85-7f61bf08c011
      version: -1
      name: Is it screenshot mode?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "23"
      "yes":
      - "29"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isTrue
          left:
            value:
              simple: inputs.screenshot mode
            iscontext: true
    view: |-
      {
        "position": {
          "x": -180,
          "y": 560
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "23":
    id: "23"
    taskid: 44098ef2-0cc4-4210-8a10-582579177c69
    type: playbook
    task:
      id: 44098ef2-0cc4-4210-8a10-582579177c69
      version: -1
      name: Checkerindi_IP
      playbookName: Checkerindi_IP
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "25"
    scriptarguments:
      ip:
        simple: ${IP}
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
      forEach: true
    view: |-
      {
        "position": {
          "x": 40,
          "y": 735
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "24":
    id: "24"
    taskid: 72c15438-bf82-4be4-82be-2577def7ffa0
    type: regular
    task:
      id: 72c15438-bf82-4be4-82be-2577def7ffa0
      version: -1
      name: Extract all IP
      description: Extract a list of IPs, URLs or Hashes from te first column of the
        CSV or every line from text file
      script: Checker|||checkerindi-extract-single
      type: regular
      iscommand: true
      brand: Checker
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
      mode:
        simple: ip
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -180,
          "y": 410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "25":
    id: "25"
    taskid: 7eec441a-9598-469f-84e7-3a9b12c386fd
    type: regular
    task:
      id: 7eec441a-9598-469f-84e7-3a9b12c386fd
      version: -1
      name: Return files
      description: Returns results from checkerindi functions by returning CSV file
        and ZIP file if screenshot mode
      script: Checker|||checkerindi-results
      type: regular
      iscommand: true
      brand: Checker
    scriptarguments:
      filename: {}
      mode:
        simple: ip
      screenshot:
        simple: "false"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 40,
          "y": 890
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "27":
    id: "27"
    taskid: 77eb3ea7-c942-4a03-8440-816af10b12fb
    type: regular
    task:
      id: 77eb3ea7-c942-4a03-8440-816af10b12fb
      version: -1
      name: Return files
      description: Returns results from checkerindi functions by returning CSV file
        and ZIP file if screenshot mode
      script: Checker|||checkerindi-results
      type: regular
      iscommand: true
      brand: Checker
    scriptarguments:
      filename: {}
      mode:
        simple: ip
      screenshot:
        simple: "true"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -410,
          "y": 890
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "29":
    id: "29"
    taskid: 806e8e88-583f-4b2f-8274-f1773a468871
    type: playbook
    task:
      id: 806e8e88-583f-4b2f-8274-f1773a468871
      version: -1
      name: Checkerindi_IP_Screenshot
      playbookName: Checkerindi_IP_Screenshot
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "27"
    scriptarguments:
      ip:
        simple: ${IP}
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
      forEach: true
    view: |-
      {
        "position": {
          "x": -410,
          "y": 735
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 695,
        "width": 830,
        "x": -410,
        "y": 290
      }
    }
  }
inputs:
- key: file
  value:
    simple: ${File}
  required: false
  description: File reputation check
  playbookInputQuery:
- key: screenshot mode
  value:
    complex:
      root: incident
      filters:
      - - operator: containsString
          left:
            value:
              simple: incident.details
            iscontext: true
          right:
            value:
              simple: screenshot
      accessor: details
      transformers:
      - operator: substringFrom
        args:
          from:
            value:
              simple: screenshot
      - operator: trim
      - operator: toLowerCase
  required: false
  description: ""
  playbookInputQuery:
outputs:
- contextPath: DBotScore.Indicator
- contextPath: IP.Address
- contextPath: IP.VirusTotal.Score
- contextPath: IP.VirusTotal.Malicious
fromversion: 5.0.0
tests:
- No tests (auto formatted)
