id: Checker_Extract
version: -1
name: Checker_Extract
description: 'All-in-one automation: Extracts ip, url and hash from CSV or Text file
  and checks reputation of all the indicators found. '
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 00c9bd21-d50a-46b7-8091-1825851942a5
    type: start
    task:
      id: 00c9bd21-d50a-46b7-8091-1825851942a5
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 4d9f2ccb-4d69-454a-8828-ff9f8db51b19
    type: regular
    task:
      id: 4d9f2ccb-4d69-454a-8828-ff9f8db51b19
      version: -1
      name: Check Reputation of extracted IOCs
      description: Extracts IOCs from attached file automatically and does reputation
        checks
      script: Checker|||checker-extract
      type: regular
      iscommand: true
      brand: Checker
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
      file:
        simple: ${inputs.file}
      screenshot:
        simple: ${inputs.screenshot mode}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 220
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 265,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs:
- key: file
  value:
    simple: ${File}
  required: false
  description: ""
  playbookInputQuery:
- key: screenshot mode
  value:
    complex:
      root: incident
      filters:
      - - operator: containsGeneral
          left:
            value:
              simple: incident.details
            iscontext: true
          right:
            value:
              simple: screenshot
      accessor: details
      transformers:
      - operator: substringFrom
        args:
          from:
            value:
              simple: screenshot
      - operator: trim
      - operator: toLowerCase
  required: false
  description: ""
  playbookInputQuery:
outputs:
- contextPath: IP.Reputation
  type: unknown
- contextPath: IP
  type: unknown
fromversion: 5.0.0
tests:
- No tests (auto formatted)
