id: d1bb49d2-a39e-4341-8f8f-c40a4e2a1437
version: 7
name: Checkerindi_Batch_URL
description: URL reputation check is carried out from a list of urls provided in csv
  or text file.  CSV or text file should contain a column (1st column) of urls without
  headers.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 19d04886-0fc6-401c-8d7c-7ce8d4881877
    type: start
    task:
      id: 19d04886-0fc6-401c-8d7c-7ce8d4881877
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "24"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -180,
          "y": 290
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "21":
    id: "21"
    taskid: 4f2fd971-ac05-4cb0-8d85-7f61bf08c011
    type: condition
    task:
      id: 4f2fd971-ac05-4cb0-8d85-7f61bf08c011
      version: -1
      name: Is it screenshot mode?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "28"
      "yes":
      - "29"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isTrue
          left:
            value:
              simple: inputs.screenshot mode
            iscontext: true
    view: |-
      {
        "position": {
          "x": -180,
          "y": 560
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "24":
    id: "24"
    taskid: 25241d41-1024-4bad-8067-ede789f3606a
    type: regular
    task:
      id: 25241d41-1024-4bad-8067-ede789f3606a
      version: -1
      name: Extract all URL
      description: Extract a list of IPs, URLs or Hashes from te first column of the
        CSV or every line from text file
      script: Checker|||checkerindi-extract-single
      type: regular
      iscommand: true
      brand: Checker
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
      mode:
        simple: url
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -180,
          "y": 410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "25":
    id: "25"
    taskid: ff749c2b-1489-4570-867b-974287958c43
    type: regular
    task:
      id: ff749c2b-1489-4570-867b-974287958c43
      version: -1
      name: Return files
      description: Returns results from checkerindi functions by returning CSV file
        and ZIP file if screenshot mode
      script: Checker|||checkerindi-results
      type: regular
      iscommand: true
      brand: Checker
    scriptarguments:
      filename: {}
      mode:
        simple: url
      screenshot:
        simple: "false"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 40,
          "y": 890
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "27":
    id: "27"
    taskid: a1086e24-eaa6-4473-8973-bdbf1b846fae
    type: regular
    task:
      id: a1086e24-eaa6-4473-8973-bdbf1b846fae
      version: -1
      name: Return files
      description: Returns results from checkerindi functions by returning CSV file
        and ZIP file if screenshot mode
      script: Checker|||checkerindi-results
      type: regular
      iscommand: true
      brand: Checker
    scriptarguments:
      filename: {}
      mode:
        simple: url
      screenshot:
        simple: "true"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -410,
          "y": 890
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "28":
    id: "28"
    taskid: aa2f2a8b-81dd-4e09-8079-e577d151a424
    type: playbook
    task:
      id: aa2f2a8b-81dd-4e09-8079-e577d151a424
      version: -1
      name: Checkerindi_URL
      playbookName: Checkerindi_URL
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "25"
    scriptarguments:
      url:
        simple: ${URL}
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
      forEach: true
    view: |-
      {
        "position": {
          "x": 40,
          "y": 735
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "29":
    id: "29"
    taskid: a970f7e8-6b4e-4ed0-8451-3ae861fc3ddc
    type: playbook
    task:
      id: a970f7e8-6b4e-4ed0-8451-3ae861fc3ddc
      version: -1
      name: Checkerindi_URL_Screenshot
      playbookName: Checkerindi_URL_Screenshot
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "27"
    scriptarguments:
      url:
        simple: ${URL}
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
      forEach: true
    view: |-
      {
        "position": {
          "x": -410,
          "y": 735
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 695,
        "width": 830,
        "x": -410,
        "y": 290
      }
    }
  }
inputs:
- key: file
  value:
    simple: ${File}
  required: false
  description: File reputation check
  playbookInputQuery: null
- key: screenshot mode
  value:
    complex:
      root: incident
      filters:
      - - operator: containsString
          left:
            value:
              simple: incident.details
            iscontext: true
          right:
            value:
              simple: screenshot
      accessor: details
      transformers:
      - operator: substringFrom
        args:
          from:
            value:
              simple: screenshot
      - operator: trim
      - operator: toLowerCase
  required: false
  description: ""
  playbookInputQuery: null
outputs:
- contextPath: DBotScore.Indicator
- contextPath: IP.Address
- contextPath: IP.VirusTotal.Score
- contextPath: IP.VirusTotal.Malicious
sourceplaybookid: 46bbae12-8fbc-4f3a-83a1-772e35af3e85
