id: 58dca95a-1fae-47e3-893a-683bd962549b
version: 4
name: Checkerindi_File_Screenshot
description: Checks for file reputation using Virus Total. Used as sub-playbook.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: df3f43a7-2c41-4a80-88c3-9be86798d166
    type: start
    task:
      id: df3f43a7-2c41-4a80-88c3-9be86798d166
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 61e12a37-5a28-42fc-8875-2aed36ee87b3
    type: regular
    task:
      id: 61e12a37-5a28-42fc-8875-2aed36ee87b3
      version: -1
      name: Virus Total File
      description: Checks virus total reputation for ip or url or hash or file
      script: Checker|||checkerindi-virustotal
      type: regular
      iscommand: true
      brand: Checker
    scriptarguments:
      indicator:
        simple: ${inputs.file}
      mode:
        simple: file
      screenshot:
        simple: "true"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs:
- key: file
  value:
    simple: ${File.EntryID}
  required: false
  description: File
  playbookInputQuery: null
outputs:
- contextPath: File.MD5
- contextPath: File.SHA1
- contextPath: File.SHA256
- contextPath: DBotScore.Indicator
- contextPath: DBotScore.Type
- contextPath: DBotScore.Vendor
- contextPath: DBotScore.Score
- contextPath: Checker.File.VirusTotal.score
- contextPath: Checker.File.VirusTotal.malicious
sourceplaybookid: b56d427f-15bd-4df3-85c8-83b59803b9b3
